name: TelePadPlugin
main: se.fredsfursten.telepadplugin.TelePadPlugin
version: 0.1-DEV
author: vanbrayne
description: A Minecraft plugin for so called "Jump Pad" functionality
commands:
  telepad:
    description: Control jump pads
    usage: /telepad add| remove | edit | goto | list 
    permission-message: You don't have <permission>
permissions:
  telepad.*:
    description: Gives access to all telepad commands
    default: op
    telepad.add: true
    telepad.target: true
    telepad.remove: true
    telepad.edit: true
    telepad.list: true
    telepad.goto: true
  telepad.add:
    description: Access to /telepad add command
    default: op
  telepad.target:
    description: Access to /telepad target command
    default: op
  telepad.remove:
    description: Access to /telepad remove command
    default: op
  telepad.edit:
    description: Access to /telepad edit command
    default: op
  telepad.list:
    description: Access to /telepad list command
    default: op
  telepad.goto:
    description: Access to /telepad goto command
    default: op
  telepad.jump:
    description: Can jump from a telepad
    default: op
