name: TelePadPlugin
main: se.fredsfursten.telepadplugin.TelePadPlugin
version: 2.0
author: vanbrayne
description: A Minecraft plugin for so called "Jump Pad" functionality
depend: [EithonLibraryPlugin]
commands:
  telepad:
    description: Control jump pads
    usage: /telepad add | link | remove  | goto | list | reload
    permission-message: You don't have <permission>
permissions:
  telepad.*:
    description: Gives access to all telepad commands
    default: op
    telepad.add: true
    telepad.link: true
    telepad.reload: true
    telepad.remove: true
    telepad.list: true
    telepad.goto: true
  telepad.add:
    description: Access to /telepad add command
    default: op
  telepad.link:
    description: Access to /telepad link command
    default: op
  telepad.remove:
    description: Access to /telepad remove command
    default: op
  telepad.list:
    description: Access to /telepad list command
    default: op
  telepad.goto:
    description: Access to /telepad goto command
    default: op
  telepad.reload:
    description: Access to /telepad reload command
    default: op
  telepad.jump:
    description: Can jump from a telepad
    default: op
